version: '3'

volumes:
  messaging_app_mysql:
    driver: root

services:
  messaging_app_mysql:
    image: mysql:8.0.30
    container_name: messaging_app_mysql
    volumes:
      - ./docker/provision/mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
