-- Variables
SET @TEST_DATABASE = '';
SET @DEVELOPMENT_DATABASE = '';
SET @PRODUCTION_DATABASE = '';
SET @TEST_USER = '';
SET @PROD_USER = '';
SET @DEV_USER = '';
SET @TEST_USER_PASS = '';
SET @PROD_USER_PASS = '';
SET @DEV_USER_PASS = '';

-- Create databases
SET @SQL = CONCAT('CREATE DATABASE IF NOT EXISTS `', @TEST_DATABASE, '`;');
PREPARE stmt FROM @SQL;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @SQL = CONCAT('CREATE DATABASE IF NOT EXISTS `', @DEVELOPMENT_DATABASE, '`;');
PREPARE stmt FROM @SQL;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @SQL = CONCAT('CREATE DATABASE IF NOT EXISTS `', @PRODUCTION_DATABASE, '`;');
PREPARE stmt FROM @SQL;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Create users and grant rights
SET @SQL = CONCAT('CREATE USER IF NOT EXISTS ''', @TEST_USER, '''@''%'' IDENTIFIED BY ''', @TEST_USER_PASS, ''';');
PREPARE stmt FROM @SQL;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @SQL = CONCAT('GRANT 
    CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT 
    ON *.* TO ''', @TEST_USER, '''@''%'';');
PREPARE stmt FROM @SQL;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @SQL = CONCAT('CREATE USER IF NOT EXISTS ''', @PROD_USER, '''@''%'' IDENTIFIED BY ''', @PROD_USER_PASS, ''';');
PREPARE stmt FROM @SQL;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @SQL = CONCAT('GRANT 
    CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT 
    ON *.* TO ''', @PROD_USER, '''@''%'';');
PREPARE stmt FROM @SQL;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @SQL = CONCAT('CREATE USER IF NOT EXISTS ''', @DEV_USER, '''@''%'' IDENTIFIED BY ''', @DEV_USER_PASS, ''';');
PREPARE stmt FROM @SQL;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @SQL = CONCAT('GRANT 
    CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT 
    ON *.* TO ''', @DEV_USER, '''@''%'';');
PREPARE stmt FROM @SQL;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

FLUSH PRIVILEGES;