name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint

  build_and_test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build --if-present
      - name: Run tests
        run: npm test
