name: Pull Request lint & test
run-name: New changes pushed by @${{ github.actor }}, starting new pipeline process 🚀
on:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint

  Integration-test:
    needs: Lint
    runs-on: ubuntu-latest
    environment: development
    services:
      mysql:
        image: mysql:8.0.30
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - '${{ vars.MYSQL_PORT }}:3306'
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Create env
        run: echo "${{ secrets.ENV_DOT_TEST }}" > .env.test

      - name: Install dependencies
        run: npm install
      - name: Migrate Database
        run: npm run db:deploy:test
      - name: Run tests
        run: npm test
