name: Test and Build
run-name: New changes pushed by @${{ github.actor }}, starting new pipeline process 🚀
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    environment: test
    services:
      db:
        image: mysql:8.0.30
        ports:
          - 33060
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      # - name: Install Ubuntu dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install libcurl4-openssl-dev libmysqlclient-dev libgirepository1.0-dev
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Migrate Database
        run: npm run db:deploy:test
      - name: Run tests
        run: npm test
