name: Pull Requests
run-name: pull request checking
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - BE-MessagingApp-Pipeline-test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ vars.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
          MYSQL_USER: ${{ vars.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ vars.MYSQL_PASSWORD }}
        ports:
          - 127.0.0.1:33060:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create env file
        run: |
          echo "${{ vars.TEST_DOT_ENV }}" > .env.test
          echo "${{ vars.TEST_DOT_ENV }}" > .env
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Migrate Database
        run: npm run db:deploy:test
      - name: Run tests
        run: npm test
