name: Pull Requests
run-name: pull request checking
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - BE-MessagingApp-Pipeline-test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.30
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        ports:
          - '${{ env.MYSQL_PORT }}:3306'
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Create env
        run: echo "DATABASE = ${{ secrets.ENV_DOT_TEST }}" > .env.test

      - name: Install dependencies
        run: npm install
      - name: Migrate Database
        run: npm run db:deploy:test
      - name: Run tests
        run: npm test
